import type { Metadata } from 'next';
import Overview from './dashboard/overview';

export const metadata: Metadata = {
  title: 'Admin',
  description: 'Generated by create next app',
};

export default function AdminPage() {
  return (
    <div>
      <Overview />
    </div>
  );
}
